# -*- coding: utf-8 -*-
"""numpy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJnOugeafGnfrG8MCmB14lf23txqD10g
"""

import numpy as np

#numpy array normal
arr = np.array([1,2,3])
print(arr)

#numpy array matriz
mtz = np.array([[1,2,3],[4,5,6],[7,8,9]])

#numpy array matriz tudo igual
m= np.ones([3,3])

#array normal até numero-1
r = np.arange(6)

#array normal inicio,fim-1, pula
i = np.arange(7,23,3)

print(arr)
print(mtz)
print(m)
print(r)
print(i)