# -*- coding: utf-8 -*-
"""numpy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJnOugeafGnfrG8MCmB14lf23txqD10g
"""

import numpy as np

arr = np. arange(6)
m = arr.reshape(3,2) # modela vetor para matriz lxc

print(m)
print(m.size) # retorna o tamanho de um NumPy Array
print(m.ndim) # retorna o número de dimensões de um NumPy Array
print(m.shape) # retorna formato

print(m.sum(axis=0)) #soma coluna
print(m.sum(axis=1)) #som linha

print(m*5) #todos elementos multiplica
print(m/2) #todos elementos divide