# -*- coding: utf-8 -*-
"""numpy4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJnOugeafGnfrG8MCmB14lf23txqD10g
"""

import numpy as np

a=np.random.seed(10) #garantir que o aleatorio sera igual
a=np.random.randint(20,50,[5,5]) #gera 5x5 numeros de 20 a 50
print(a)
print(np.unique(a)) #extrai elemetos unicos do array
print(np.unique(a, return_counts = True)) #quantas vezez um elemento se repete