# -*- coding: utf-8 -*-
"""numpy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJnOugeafGnfrG8MCmB14lf23txqD10g
"""

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3=np.concatenate([arr, arr2]) #juntar array

print(arr1.min(), arr1.max()) #valores
print(arr1.argmin(),arr1.argmax()) #indice
print(arr2.sum(), arr2.mean()) #soma e media
print(arr1 + arr2) #operação entre array
print(arr3)